### ISSUE TITLE
New release only works with { shadow: true }

### ISSUE THREAD

**Issue by VitalyBrusentsev** [bitovi/react-to-webcomponent#10]
After upgrading to 1.5.0 I've noticed that my component has disappeared from the page. 
Changing the invocation to include `{ shadow: true }` has restored the rendering (but obviously introduced the shadow dom CSS isolation).

You can see this issue here: 
https://webcomponents.dev/edit/VB8Z27H6TnQa9ojTBQ8P?pm=1
This statement does not work:
```
customElements.define(
  "my-counter",
  reactToWebComponent(MyCounter, React, ReactDOM)
);
```
This does:
```
customElements.define(
  "my-counter",
  reactToWebComponent(MyCounter, React, ReactDOM, { shadow: true })
);

```

**Comment by VitalyBrusentsev** [comment]
@cherifGsoul is it possible to fix the issue, to enable both Shadow and non-Shadow options to work?

**Comment by cherifGsoul** [comment]
Hey @VitalyBrusentsev, thank you for reporting the issue, I'll discuss it with the team and get back to you!

**Comment by cherifGsoul** [comment]
@VitalyBrusentsev It is fixed and released, let's us know if you face any other issues.
Thank you.
