### ISSUE TITLE
Styling component

### ISSUE THREAD

**Issue by majordo** [bitovi/react-to-webcomponent#11]
Is it possible to style component with external css file?
...Or only with inline styling?

**Comment by RathodSanjayL** [comment]
@majordo same I faced 

I need an external style for the component

**Comment by VitalyBrusentsev** [comment]
If you use the Shadow DOM (default) mode, all external styles are ignored, that's the point of Shadow DOM, to isolate your component from the host styling.
The last release broke the non-Shadow DOM option (see issue #10) , and there is no fix in sight. So you can downgrade to
```
    "react-to-webcomponent": "^1.4.0"
```
and use external styling.

**Comment by majordo** [comment]
@VitalyBrusentsev thanks

**Comment by justinbmeyer** [comment]
We have fixed this in the new release

**Comment by chriszrc** [comment]
But what about css modules? Can't these be added inside the shadowdom root?

**Comment by subramanian-iouring** [comment]
@majordo @VitalyBrusentsev 
How to use external style for the component?

**Comment by VitalyBrusentsev** [comment]
@subramanian-iouring  External, as in "defined in the app that includes this web component"? Then just set `{ shadow: false }` in your registration. All external styles will affect the component's markup. (Just make sure you use the fixed version).
If you meant "located in an external .css file", then you can render a `<link>` tag inside your component.

**Comment by subramanian-iouring** [comment]
> @subramanian-iouring External, as in "defined in the app that includes this web component"? Then just set `{ shadow: false }` in your registration. All external styles will affect the component's markup. (Just make sure you use the fixed version). If you meant "located in an external .css file", then you can render a `<link>` tag inside your component.

@VitalyBrusentsev  Thanks for your quick reply. 
I want shadow root for my component (custom-button), so i use {shadow: "open"}.  
When i use this "custom-button" component in other application, the styles are applied.

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM#applying_styles_inside_the_shadow_dom


So, how to applying styles inside the shadow DOM in r2wc?
