### ISSUE TITLE
Calling a method in React from Webcomponent

### ISSUE THREAD

**Issue by japhill** [bitovi/react-to-webcomponent#13]
Is there a way to call method in a React Component from my web component?  For instance, I render the react component as a webcomponent.  After using the react component to perform tasks and generate data, I would like to access that data from my web component.  After my webcomponent closes, I would like to call a function in the React Component to get data and pass it to another process.

**Comment by justinbmeyer** [comment]
Yes, we might be able to setup the proxy to return a method on a class-based react component.

**Comment by justinbmeyer** [comment]
I think this is possible

**Comment by justinbmeyer** [comment]
@christopherjbaker what does it mean to call a function on a traditional react component?

**Comment by justinbmeyer** [comment]
What do you mean by "web component closes"?

**Comment by nzaytsev** [comment]
Hello @janebitovi! It seems like this issue should be reopened as this functionality is unavailable in versions ^2.x.x. Or I missed something?

**Comment by bmomberger-bitovi** [comment]
The functionality that is proposed in https://github.com/bitovi/react-to-web-component/issues/13#issuecomment-1130756561 is available.  You will not be able to inspect into a React component from the web component our outside, but you can use the `function` prop converter to pass handler functions into the component, which can then communicate data to the outside world.
