### ISSUE TITLE
Jest test failed: Jest encountered an unexpected token

### ISSUE THREAD

**Issue by Sergey0s** [bitovi/react-to-webcomponent#14]
Hey, thanks for the nice module.
But I have some problem with jest test.
My app created via npx create react app plus I add Eslint and prettier
Then I'm running npm run test a I've got this error:

`> frontend@0.1.0 test /Users/username/PycharmProjects/timetables/frontend
> react-scripts test "a"
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/username/PycharmProjects/timetables/frontend/node_modules/react-to-webcomponent/react-to-webcomponent.js:31
    export default function(ReactComponent, React, ReactDOM, options= {}) {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

       5 | // eslint-disable-next-line @typescript-eslint/ban-ts-comment
       6 | // @ts-ignore
    >  7 | import reactToWebComponent from 'react-to-webcomponent';
         | ^
       8 | 
       9 | const App: React.FunctionComponent = () => {
      10 |     return (

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/App.tsx:7:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.206 s
Ran all test suites matching /a/i.`

My package.json: 
`{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@revel/core": "^5.0.1",
    "@revel/icons": "^5.0.1",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.3",
    "@testing-library/user-event": "^12.6.0",
    "@types/jest": "^26.0.20",
    "@types/node": "^12.19.13",
    "@types/react": "^16.14.2",
    "@types/react-dom": "^16.9.10",
    "postcss": "^8.2.4",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "react-to-webcomponent": "^1.5.1",
    "typescript": "^4.1.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "create-component": "rollup -c"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@rollup/plugin-image": "^2.0.6",
    "eslint-config-prettier": "^7.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.22.0",
    "postcss-loader": "^4.1.0",
    "prettier": "2.2.1",
    "rollup": "2.36.2",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-copy": "^3.3.0",
    "rollup-plugin-minify-html-literals": "^1.2.5",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-postcss": "^4.0.0",
    "rollup-plugin-replace": "^2.2.0",
    "rollup-plugin-typescript2": "^0.26.0",
    "rollup-watch": "^4.3.1",
    "typings": "^2.1.1"
  }
}`

**Comment by Sergey0s** [comment]
I added this to package.json and it did the trick!
` "jest": {
  "transformIgnorePatterns": [
    "/node_modules/(?!react-to-webcomponent)"
  ]}`

**Comment by justinbmeyer** [comment]
Thanks for the tip!

I wonder if there's a way to tell jest to ignore us ...
