### ISSUE TITLE
Properties not working with TypeScript

### ISSUE THREAD

**Issue by nhajratw** [bitovi/react-to-webcomponent#16]
It seems that passing properties doesn't work with Typescript. Does it only work if you're using the PropTypes package?

```
interface MyProps {
    data: string
}

class App extends React.Component<MyProps, any> {
    render() {
        return (
            <div className="App">
                    <p>
                        - Data: [{this.props.data}]
                    </p>
            </div>
        );
    }
}

export default App;
```

**Comment by terrabythia** [comment]
Yes, if you [look at the source code](https://github.com/bitovi/react-to-webcomponent/blob/35456df394db924db30c08ed57f8a2956a1bae69/react-to-webcomponent.js#L106), it specifically checks which properties are added to `MyReactComponent.propTypes` object and watches those for changes. You will have to include the PropTypes package for this. 

You could try to just set `MyReactComponent.propTypes` like this without importing the PropTypes package, since the script only looks at the keys of that property of your react component:

```
MyElement.propTypes = {
  propOne: 'propOne',
  propTwo: 'propTwo',
}
```

**Comment by justinbmeyer** [comment]
Thanks for the feedback @terrabythia

**Comment by justinbmeyer** [comment]
We could add a note that you still need propTypes, even with TypeScript

**Comment by janebitovi** [comment]
related to #5 - adding the null check suggested there [is problematic too](https://github.com/bitovi/react-to-webcomponent/issues/5#issuecomment-672334832), propTypes is required

**Comment by christopherjbaker** [comment]
We will very shortly add a note to the readme and warning to the code about propTypes. We are also going to remove the requirement of propTypes, but we need to research if there's a way to remove it entirely, or if we just need to provide an alternate way of providing the information we need.

**Comment by janebitovi** [comment]
https://github.com/bitovi/react-to-webcomponent/pull/50

**Comment by christopherjbaker** [comment]
We are working on the next version that has a much simpler way to provide that information. using `react-docgen-typescript` would require integrating it with the build step instead of just run time so it might complicate things, but we could certainly look into it in the future.

**Comment by alan-cooney** [comment]
It would be cool to just default to passing across all props, if no prop-types are set.

**Comment by christopherjbaker** [comment]
@alan-cooney The problem is that we get updates from the DOM. Some need to be passed to the component, some need to be passed to the underlying element. For now, the only way we can tell which we need to do is by comparing with the props definition. We are exploring more options in v2 though.
