### ISSUE TITLE
CamelCase property should be reflected to dashed attributes

### ISSUE THREAD

**Issue by psamusev** [bitovi/react-to-webcomponent#17]
Current approach assume attributes in same name as properties, however for complex names, i.e. 'pureString` attribute name should be considered in dashed style (or at least let the possibility to specify the attribute name)

**Comment by psamusev** [comment]
Please see the proposed idea in PR

**Comment by justinbmeyer** [comment]
Thanks for the PR!

**Comment by justinbmeyer** [comment]
I think we need to update the readme along with the PR
