### ISSUE TITLE
Ready for React 18 interface?

### ISSUE THREAD

**Issue by davidNHK** [bitovi/react-to-webcomponent#22]
The render API has changed since react 17 

```js
// Before
import { render } from 'react-dom';
const container = document.getElementById('app');
render(<App tab="home" />, container);

// After
import { createRoot } from 'react-dom/client';
const container = document.getElementById('app');
const root = createRoot(container);
root.render(<App tab="home" />);
```

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

Do you have plan to support it ?

**Comment by justinbmeyer** [comment]
Yes, we will support it!

**Comment by ramaramesh11** [comment]
We are planning to release it by end of next week

**Comment by nvdbleek** [comment]
Thanks for adding support for React 18, it works like a charm for me when using the latest code from master. 🌮

**Comment by bahag-xvisnei** [comment]
> We are planning to release it by end of next week

I found this package and love it. First didn't work. Now I know why. It is React 18. Waiting for the new release to publish my react web component.
