### ISSUE TITLE
Exporting to js file?

### ISSUE THREAD

**Issue by alienfacepalm** [bitovi/react-to-webcomponent#3]
Is there a way to export this as a bundled js file kinda like Stencil?

**Comment by gino8080** [comment]
same important question

**Comment by aveiga** [comment]
Hi @gino8080 and @alienfacepalm,

I've stumbled through this while searching for something else... I'm doing the bundling and exporting to a single JS file using Rollup. Here's my rollup.config.js:
`import typescript from "rollup-plugin-typescript2";
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import replace from "rollup-plugin-replace";

export default {
  input: "./src/index.tsx",
  output: {
    file: "./dist/bundle.js",
    sourcemap: true
  },
  format: "esm",
  plugins: [
    resolve({
      browser: true
    }),
    replace({
      "process.env.NODE_ENV": JSON.stringify("production")
    }),
    typescript(),
    commonjs({
      include: ["node_modules/**"],
      exclude: ["**/*.stories.js"],
      namedExports: {
        "node_modules/react/index.js": [
          "Children",
          "Component",
          "PropTypes",
          "createElement",
          "useState",
          "useEffect"
        ],
        "node_modules/react-dom/index.js": ["render"]
      }
    })
  ]
};
`
Extract from [this GitHub repo](http://github.com/aveiga/web-components-comparison/tree/master/react)

**Comment by justinbmeyer** [comment]
It already is a bundled file: https://unpkg.com/react-to-webcomponent/dist/react-to-webcomponent.js. Is this what you are looking for?

**Comment by justinbmeyer** [comment]
We will put a link to this on the readme so people know about it.
