### ISSUE TITLE
Console error: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client"

### ISSUE THREAD

**Issue by arminbashizade** [bitovi/react-to-webcomponent#42]
I think a param should be added to pass `createRoot` here:
https://github.com/bitovi/react-to-webcomponent/blob/1b11c42d840d638388ca5bf933ab0f088ed9f983/react-to-webcomponent.js#L30-L39

Error: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client"
![image](https://user-images.githubusercontent.com/3442879/180497347-f0ad73b3-13fb-4ee6-82d7-3b69fec798c9.png)

**Comment by cded** [comment]
Hi @arminbashizade if you're using React18 you should do `import * as ReactDOM from "react-dom/client"` and pass ReactDOM to `reactToWebComponent()`

**Comment by christopherjbaker** [comment]
If the ReactDOM instance provided has a `createRoot`, it will be used automatically. This error happens when you `import ReactDOM from 'react-dom'` then try to call `createRoot` on that.
