### ISSUE TITLE
 ReactComponent.propTypes is undefined when dynamically inject the react build js

### ISSUE THREAD

**Issue by satty1987** [bitovi/react-to-webcomponent#5]
![image](https://user-images.githubusercontent.com/12125467/82140554-0f9be480-984d-11ea-816f-db9dbb25b57f.png)
Fix this by adding null check.

**Comment by justinbmeyer** [comment]
You are dynamically addicting React after this library is installed?

**Comment by laddhoffman** [comment]
Looks like I am encountering this as well. 
`Uncaught TypeError: right-hand side of 'in' should be an object, got undefined`
I tried this same approach in https://github.com/bitovi/react-to-webcomponent/pull/6 but then realized there's some other disconnect here. This solution just masks another problem. I get the same error when I pass in an instance of `React.Component` or `React.FC`, with or without props defined. And if I add this undefined check it gets past that and loads the component, but it's not getting props at all.

**Comment by laddhoffman** [comment]
Oh I see, this package is perhaps assuming we are using propTypes, now https://www.npmjs.com/package/prop-types.
But I am using TypeScript so I have no need for propTypes.

**Comment by laddhoffman** [comment]
Re-opened #6

**Comment by justinbmeyer** [comment]
Ah, so ReactComponent doesn't always have propTypes.  Thanks!

**Comment by leanderseige** [comment]
I think I had a similar issue and solved it like this:

```
window.addEventListener('DOMContentLoaded', (event) => {
  var root = document.getElementById("id")
  var mywc = document.createElement('mywc')
  mywc.settings = "settings"
  root.appendChild(mywc)
}
```

**Comment by christopherjbaker** [comment]
We adjusted the logic in #50 to allow an alternate prop definition besides propTypes. We cannot current get around the need for a minimal props definition at runtime, however.
