### ISSUE TITLE
Share Context or State Across components?

### ISSUE THREAD

**Issue by use-the-fork** [bitovi/react-to-webcomponent#62]
Is there a way to share context or state across components? I have multiple web components that need access to the same source of data. Is there a way I can share this data with all of them with a store of some kind? Or is this something I would have to custom code?

Thanks!

**Comment by christopherjbaker** [comment]
Each of the Web Components we create has its own React execution, so there's no React-based way to share info between them.

It should be fairly straight-forward with some external JS though, mimicking React methodology. I have not tested this, but this is the general idea:
```js
const GLOBAL_STATE_KEY = "myGlobalState"

function useGlobalState() {
  if (!window[GLOBAL_STATE_KEY]) {
    // This is where we store the current value, the setters that need to be informed of changes,
    // add/remove functions for setters, and the logic to inform those setters.
    window[GLOBAL_STATE_KEY] = {
      value: {}, // default state value
      setters: [],
      addSetter: (setter) => {
        window[GLOBAL_STATE_KEY].setters.push(setLocalState)
      },
      removeSetter: (setter) => {
        const index = window[GLOBAL_STATE_KEY].setters.indexOf(setLocalState)
        if (index > -1) {
          window[GLOBAL_STATE_KEY].setters.splice(index, 1)
        }
      },
      setState: (value) => {
        window[GLOBAL_STATE_KEY].value = value
        for (const setter of window[GLOBAL_STATE_KEY].setters) {
          setter(value)
        }
      },
    }
  }

  // We're storing the state in React's useState, but storing the setter outside React so we can call it when we need.
  const [ state, setLocalState ] = useState(window[GLOBAL_STATE_KEY].value)

  useEffect(() => {
    window[GLOBAL_STATE_KEY].addSetter(setLocalState)
    return () => window[GLOBAL_STATE_KEY].removeSetter(setLocalState)
  }, [])

  return [ state, window[GLOBAL_STATE_KEY].setState ]
}
```

**Comment by mathematikoi** [comment]
hey @christopherjbaker, being able to share context accross web components is critical and would enable many things (all things react really).

i tried to do something about it by writing an events-based shim for react context, still wip, but can you please check this out https://github.com/mathematikoi/eventually

**Comment by rafal-zelek** [comment]
I faced same challenge for the modal instance and two places that trigger it.
I simply used mobx ( https://mobx.js.org/getting-started.html ) with a singleton store instance, by exporting an instantiated store object:

```
export interface ModalStore {
  isOpen: boolean;
  open: () => void;
  close: () => void;
}

class ModalStoreImpl implements ModalStore {
  isOpen = false;

  constructor() {
    makeObservable(this, {
      isOpen: observable,
      open: action,
      close: action,
    });
    this.isOpen = false;
  }

  open = () => {
    this.isOpen = true
  };

  close = () => {
    this.isOpen = false;
  };
}

export const modalStoreSingleton: ModalStore = new ModalStoreImpl();
``` 

And now each instance of some top lvl component wrapped into a web component just uses this as observable:

```
observer(() => {return modalStoreSingleton.isOpen ? <div>open modal</div> : <div>closed modal</div>});
```
