### ISSUE TITLE
Support css modules when enabling shadowdom 

### ISSUE THREAD

**Issue by chriszrc** [bitovi/react-to-webcomponent#63]
With a standard cra project using mui, I can configure mui to inject the emotion styles in the shadowroot, but I can't find any directions/info about injecting the css modules style/link tags in the shadowroot. If this isn't supported, seems like important functionality

**Comment by christopherjbaker** [comment]
Unfortunately, this isn't something we can control. When shadow mode is enabled, the inner contents are isolated from the rest of the page's styles, meaning those style must be _inside_ the component. I have been unable to find a way to tell CSS modules to inject its styles anywhere but the `<head>`. If you can find support for that, we can look into how we can make this work with CSS modules. You can see a [previous, more in-depth conversation](https://github.com/bitovi/react-to-webcomponent/issues/21#issuecomment-1367714666) too.

**Comment by ToinePK** [comment]
Please see my comment here:
https://github.com/bitovi/react-to-web-component/issues/21#issuecomment-2136756446
