### ISSUE TITLE
Uncaught TypeError: Cannot delete property '__reactFiber$towahsieci' of [object Object]

### ISSUE THREAD

**Issue by op30132** [bitovi/react-to-webcomponent#65]
when I use web component in React, it will cause error
`Uncaught TypeError: Cannot delete property '__reactFiber$towahsieci' of [object Object]`

but it's ok when I use web component simple in pure html,js file, is there a way to solve the problem? Thanks!

**Comment by christopherjbaker** [comment]
I've not seen this issue, @op30132. Could you put together a codesandbox that reproduces it with minimal code? We have a [template](https://codesandbox.io/s/react-to-webcomponent--basic-vqs8cl) you can use to start.
