### ISSUE TITLE
ref print out result is '[Object object]'

### ISSUE THREAD

**Issue by Monkey-47** [bitovi/react-to-webcomponent#67]
### Discussed in https://github.com/bitovi/react-to-webcomponent/discussions/66

<div type='discussions-op-text'>

<sup>Originally posted by **Monkey-47** January 29, 2023</sup>
```js
// web component:
const demoComponent = (props)=>{
useEffect(()=>{
   console.log(props.myref) // log => '[Object object]'  ❌why? why i can not get correct ref object
},[props])

return <div>...</div>
}
class WebComRef extends reactToWebComponent(React.forwardRef(demoComponent), React, ReactDOM, {
    props: {
        myref:'ref',
    },
}) {}
customElements.define('demo-component', WebComRef);

//==================
// use:
const demo = ()=>{
      const ref = useRef();
      return <demo-component myref={ref}></demo-component>
}
```

</div>

**Comment by christopherjbaker** [comment]
When React (or any other system) renders a web component, it passes everything to the browser for rendering, then the browser initializes the web component with that information. The problem you're running into is that web component attributes can only be strings or booleans, so your ref is being stringified by the browser at render time.

Good news for you though! We have a section in our docs on [how to work with `refs` specifically](https://github.com/bitovi/react-to-webcomponent/blob/main/docs/api.md#ref-props) that should get you up and running quick.
