### ISSUE TITLE
CodePen Example Not Working

### ISSUE THREAD

**Issue by sgerhardt** [bitovi/react-to-webcomponent#79]
The CodePen example from the README doesn't display the greeting https://codepen.io/weasyv/pen/BarBWvM?editors=1010 .

It looks like the file that's used in the [script element](https://unpkg.com/react-to-webcomponent/dist/react-to-webcomponent.js)  can't be found.

We did note that the example on code sandbox _does_ appear to work though that implementation looks different.

**Comment by christopherjbaker** [comment]
Thanks for catching that! We changed the build naming convention and never updated that example. We also added a more comprehensive example in Code Sandbox.
